import { pgTable, uuid, text, integer, numeric, date, timestamp, boolean, index, uniqueIndex } from 'drizzle-orm/pg-core'

export const users=pgTable('users',{id:uuid('id').defaultRandom().primaryKey(),name:text('name').notNull(),email:text('email').notNull().unique(),passwordHash:text('password_hash'),createdAt:timestamp('created_at').defaultNow().notNull(),updatedAt:timestamp('updated_at').defaultNow().notNull()})
export const authSessions=pgTable('auth_sessions',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),tokenHash:text('token_hash').notNull().unique(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull()},t=>[index('auth_sessions_user_idx').on(t.userId),index('auth_sessions_expiry_idx').on(t.expiresAt)])
export const nutritionGoals=pgTable('nutrition_goals',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),calories:integer('calories').notNull().default(2200),protein:numeric('protein').notNull().default('150'),carbs:numeric('carbs').notNull().default('250'),fat:numeric('fat').notNull().default('70'),water:numeric('water').notNull().default('3'),updatedAt:timestamp('updated_at').defaultNow().notNull()},t=>[uniqueIndex('goals_user_idx').on(t.userId)])
export const foodEntries=pgTable('food_entries',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),date:date('date').notNull(),mealType:text('meal_type').notNull(),foodName:text('food_name').notNull(),servingSize:text('serving_size').notNull(),calories:numeric('calories').notNull(),protein:numeric('protein').notNull(),carbs:numeric('carbs').notNull(),fat:numeric('fat').notNull(),imageUrl:text('image_url'),confidence:numeric('confidence'),createdAt:timestamp('created_at').defaultNow().notNull()},t=>[index('food_user_date_idx').on(t.userId,t.date)])
export const challenges=pgTable('winter_arc_challenges',{id:uuid('id').defaultRandom().primaryKey(),userId:uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),name:text('name').notNull(),startDate:date('start_date').notNull(),endDate:date('end_date').notNull(),duration:integer('duration').notNull(),status:text('status').notNull().default('active'),createdAt:timestamp('created_at').defaultNow().notNull()},t=>[index('challenge_user_status_idx').on(t.userId,t.status)])
export const habits=pgTable('habits',{id:uuid('id').defaultRandom().primaryKey(),challengeId:uuid('challenge_id').notNull().references(()=>challenges.id,{onDelete:'cascade'}),name:text('name').notNull(),icon:text('icon').default('✓'),description:text('description'),type:text('type').notNull().default('boolean'),target:numeric('target').notNull().default('1'),unit:text('unit').notNull().default('done'),frequency:text('frequency').notNull().default('daily'),active:boolean('active').notNull().default(true),sortOrder:integer('sort_order').notNull().default(0)})
export const habitCompletions=pgTable('habit_completions',{id:uuid('id').defaultRandom().primaryKey(),habitId:uuid('habit_id').notNull().references(()=>habits.id,{onDelete:'cascade'}),date:date('date').notNull(),value:numeric('value').notNull().default('1'),completed:boolean('completed').notNull().default(true),updatedAt:timestamp('updated_at').defaultNow().notNull()},t=>[uniqueIndex('habit_date_unique').on(t.habitId,t.date),index('habit_completion_date_idx').on(t.date)])
