<script setup lang="ts">
const file=ref<File>(),preview=ref(''),busy=ref(false),saving=ref(false),result=ref<any>(),meal=ref('Lunch'),error=ref('')
const {refresh}=useNutrition()
function select(f?:File){if(!f)return;if(!f.type.startsWith('image/')){error.value='Choose an image file.';return}file.value=f;preview.value=URL.createObjectURL(f);result.value=null;error.value=''}
async function analyze(){if(!file.value)return;busy.value=true;error.value='';try{const body=new FormData();body.append('image',file.value);result.value=await $fetch('/api/food/analyze',{method:'POST',body})}catch(e:any){error.value=e.data?.statusMessage||'Analysis failed. Try again.'}finally{busy.value=false}}
async function save(){saving.value=true;try{await $fetch('/api/food',{method:'POST',body:{...result.value,mealType:meal.value}});await refresh();await navigateTo('/todays-menu')}catch(e:any){error.value=e.data?.statusMessage||'Could not save this food.'}finally{saving.value=false}}
onBeforeUnmount(()=>{if(preview.value)URL.revokeObjectURL(preview.value)})
</script>
<template><div class="mx-auto max-w-3xl"><p class="text-sm font-medium text-emerald-700">FOOD SCANNER</p><h1 class="mt-2 text-3xl font-semibold">Scan your food</h1><p class="mt-2 text-stone-500">Take a photo or upload an image to estimate its nutrition.</p><p v-if="error" class="mt-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{{error}}</p><div class="mt-7 rounded-2xl border-2 border-dashed border-stone-300 bg-white p-6 text-center sm:p-10" @dragover.prevent @drop.prevent="select(($event as DragEvent).dataTransfer?.files[0])"><input id="food-file" class="sr-only" type="file" accept="image/*" capture="environment" @change="select(($event.target as HTMLInputElement).files?.[0])"><img v-if="preview" :src="preview" class="mx-auto max-h-80 rounded-xl object-contain" alt="Selected food"><template v-else><div class="mx-auto grid size-14 place-items-center rounded-2xl bg-emerald-50 text-2xl">📷</div><p class="mt-4 font-medium">Drop your food photo here</p><p class="mt-1 text-sm text-stone-500">or take a photo/upload an image</p></template><label for="food-file" class="mt-5 inline-block cursor-pointer rounded-xl border px-4 py-2 text-sm">{{preview?'Replace image':'Choose image'}}</label></div><button v-if="file&&!result" class="mt-5 w-full rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white disabled:opacity-60" :disabled="busy" @click="analyze">{{busy?'Analyzing image…':'Analyze food'}}</button><div v-if="busy" class="mt-5 animate-pulse rounded-2xl bg-white p-6 text-stone-500">Estimating ingredients and nutrition…</div><section v-if="result" class="mt-6 rounded-2xl bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase text-emerald-700">Estimated nutrition</p><input v-model="result.foodName" class="mt-2 w-full border-b p-1 text-xl font-semibold"><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><label v-for="k in ['servingSize','calories','protein','carbs','fat']" :key="k" class="text-xs capitalize text-stone-500">{{k}}<input v-model="result[k]" class="mt-1 w-full rounded-lg border p-2 text-sm text-stone-900"></label></div><p class="mt-4 text-sm text-stone-500">Confidence: {{Math.round(result.confidence*100)}}% · {{result.ingredients?.join(', ')}}</p><label class="mt-4 block text-sm">Meal<select v-model="meal" class="mt-1 block w-full rounded-lg border p-3"><option>Breakfast</option><option>Lunch</option><option>Snack</option><option>Dinner</option></select></label><p class="mt-4 text-xs text-stone-400">AI values are estimates. Review and adjust before saving.</p><div class="mt-5 flex gap-3"><button class="flex-1 rounded-xl bg-emerald-800 p-3 font-semibold text-white" :disabled="saving" @click="save">{{saving?'Saving…':"Add to today's menu"}}</button><button class="rounded-xl border px-4" @click="analyze">Analyze again</button></div></section></div></template>
