<script setup lang="ts">
const { data, refresh, error } = await useFetch<any>('/api/nutrition/goals')
const { data: account } = await useFetch<any>('/api/auth/me')
const goals = reactive({ calories: 2200, protein: 150, carbs: 250, fat: 70, water: 3 })
watch(data, value => { if (value) Object.assign(goals, value) }, { immediate: true })
const saved = ref(false), message = ref('')
async function save() { message.value=''; try { await $fetch('/api/nutrition/goals',{method:'PUT',body:goals}); await refresh(); saved.value=true; setTimeout(()=>saved.value=false,2500) } catch(e:any) { message.value=e.data?.statusMessage||'Could not save goals.' } }
async function signOut() { await $fetch('/api/auth/logout',{method:'POST'}); await navigateTo('/login') }
</script>
<template><div class="mx-auto max-w-3xl"><p class="text-sm text-emerald-700">MAKE IT YOURS</p><h1 class="mt-1 text-3xl font-semibold">Settings</h1><p class="mt-2 text-stone-500">Set daily nutrition targets for your routine.</p><form class="mt-7 rounded-2xl bg-white p-6 shadow-sm" @submit.prevent="save"><h2 class="font-semibold">Nutrition goals</h2><p class="mt-1 text-sm text-stone-500">Saved goals are used throughout NutriArc.</p><p v-if="error" class="mt-3 text-sm text-amber-700">Sign in and connect the database before changing goals.</p><p v-if="message" role="alert" class="mt-3 text-sm text-rose-700">{{message}}</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label v-for="field in [['calories','Calories','kcal'],['protein','Protein','g'],['carbs','Carbohydrates','g'],['fat','Fat','g'],['water','Water','L']]" :key="field[0]" class="text-sm text-stone-600">{{field[1]}}<div class="mt-1 flex items-center rounded-lg border pr-3"><input v-model.number="(goals as any)[field[0]]" type="number" min="0" step="any" required class="w-full rounded-lg p-3 outline-none"><span class="text-xs text-stone-400">{{field[2]}}</span></div></label></div><div class="mt-6 flex items-center gap-4"><button class="rounded-xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white">Save goals</button><span v-if="saved" class="text-sm text-emerald-700">Goals saved</span></div></form><section class="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-white p-6"><div><h2 class="font-semibold">Account</h2><p v-if="account" class="mt-1 text-sm text-stone-500">Signed in as {{account.email}}</p><p v-else class="mt-1 text-sm text-stone-500">Log in or create an account to save your nutrition data.</p></div><div v-if="account"><button class="rounded-xl border border-stone-200 px-4 py-2 text-sm" @click="signOut">Sign out</button></div><div v-else class="flex gap-3"><NuxtLink to="/login" class="rounded-xl border border-stone-200 px-4 py-2 text-sm">Log in</NuxtLink><NuxtLink to="/create-account" class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Create account</NuxtLink></div></section></div></template>
